name: hotpath-profile

on:
  pull_request:

permissions:
  contents: read

jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - id: head_timing_metrics
        run: |
          # Extract timing metrics from head branch
          {
            echo 'metrics<<EOF'
            cargo run --features='hotpath,hotpath-ci' --profile hotpath --bin andromeda examples/performance.ts | grep '^{"hotpath_profiling_mode"'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Checkout base
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}

      - id: base_timing_metrics
        run: |
          # Extract timing metrics from base branch
          {
            echo 'metrics<<EOF'
            cargo run --features='hotpath,hotpath-ci' --profile hotpath --bin andromeda examples/performance.ts | grep '^{"hotpath_profiling_mode"'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Save metrics to artifact
        run: |
          mkdir -p /tmp/metrics
          echo '${{ steps.head_timing_metrics.outputs.metrics }}' > /tmp/metrics/head_timing.json
          echo '${{ steps.base_timing_metrics.outputs.metrics }}' > /tmp/metrics/base_timing.json
          echo '${{ github.event.pull_request.number }}' > /tmp/metrics/pr_number.txt

      - uses: actions/upload-artifact@v4
        with:
          name: profile-metrics
          path: /tmp/metrics/
          retention-days: 1
